"""Universal structured contact ingestion for MarkOrbit Data Engine."""

CONTACT_INGEST_VERSION = "CONTACT_INGEST_V1.5"
CONTACT_SCHEMA_VERSION = "CONTACT_SCHEMA_V1.1"

__all__ = ["CONTACT_INGEST_VERSION", "CONTACT_SCHEMA_VERSION"]
