from __future__ import annotations


CONTRACT_VERSION = "MARKORBIT_DATA_ENGINE_INTEGRATION_V1"
SOURCE_OWNER = "MARKORBIT_DATA_ENGINE"
SERVICE_ROLE = "SOURCE_FACT_SERVICE"
REQUEST_ID_HEADER = "X-Request-ID"
CONTRACT_VERSION_HEADER = "X-MarkOrbit-Contract-Version"
SOURCE_OWNER_HEADER = "X-MarkOrbit-Source-Owner"
