"""Task-driven USPTO mark-image acquisition for the US domain."""

SOURCE_VERSION = "US_MARK_IMAGE_V1"
DEFAULT_REQUEST_INTERVAL_SECONDS = 2.5
DEFAULT_QUEUE_TARGET = 100_000
DEFAULT_QUEUE_FLOOR = 20_000

__all__ = [
    "SOURCE_VERSION",
    "DEFAULT_REQUEST_INTERVAL_SECONDS",
    "DEFAULT_QUEUE_TARGET",
    "DEFAULT_QUEUE_FLOOR",
]
